export const config = {
    baseUrl: 'https://random-joy.onrender.com',
    login: '/auth/login',
    register: '/auth/register',
    details: '/auth/details',
    category: '/category',
    saveInterest: '/auth/updateInterest',
    skipInterest: '/auth/skipInterest',
    asset:'/asset/random/asset',
    puzzle: '/puzzle/random',
    suggestStatement: '/commitmentandstatement/random/statement',
    suggestCommitment: '/commitmentandstatement/random/commitment',
    assignCommitment: '/commitmentandstatement/commitment',
    assignStatement: '/commitmentandstatement/statement',
    commitments: '/commitmentandstatement/user/commitment',
    notifications: '/asset/share',
    assetWithId: '/asset',
    shareAsset: '/asset/share',
    completeCommitment: '/commitmentandstatement/complete'
};
